models/Step.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tblstep".
 *
 * @property int $id
 * @property int $queue_id
 * @property string $name
 *
 * @property Tblqueue $queue
 * @property Tblinfo[] $tblinfos
 */
class Step extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tblstep';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['queue_id', 'name'], 'required'],
            [['queue_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            //[['queue_id'], 'exist', 'skipOnError' => true, 'targetClass' => Queue::className(), 'targetAttribute' => ['queue_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'queue_id' => 'Queue ID',
            'name' => 'Name',
        ];
    }

    /**
     * Gets query for [[Queue]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getQueue()
    {
        return $this->hasOne(Queue::className(), ['id' => 'queue_id']);
    }

    /**
     * Gets query for [[Tblinfos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTblinfos()
    {
        return $this->hasMany(Info::className(), ['step_id' => 'id']);
    }
}

controllers/InfoController.php
<?php

namespace app\controllers;

use app\models\Info;
use app\models\InfoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InfoController implements the CRUD actions for Info model.
 */
class InfoController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Info models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new InfoSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Info model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Info model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($step)
    {
        $model = new Info();
        $model->step_id = $step;
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Info model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Info model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Info model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Info the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Info::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/StepController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Info;
use app\models\InfoSearch;
use yii\helpers\ArrayHelper;
use app\models\Model;
use app\models\Step;
use app\models\StepSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * StepController implements the CRUD actions for Step model.
 */
class StepController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return 
        array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                   // 'only' => ['logout'],
                    'rules' => [
                        [
                            'actions' => ['create', 'index', 'update', 'view', 'delete'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                        [
                            'actions' => ['login'],
                            'allow' => true,
                            // 'roles' => ['?'],
                        ],
                        
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Step models.
     *
     * @return string
     */
    public function actionIndex($queue)
    {
        $searchModel = new StepSearch();
        $dataProvider = $searchModel->search($queue, $this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'queue' => $queue,
        ]);
    }

    /**
     * Displays a single Step model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $searchInfo = new InfoSearch();
        $dataProvider = $searchInfo->search($id, $this->request->queryParams);


        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchInfo' => $searchInfo,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Step model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($queue)
    {
        $model = new Step();
        $modelsinfo = [new Info];
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) ) {

                $modelsinfo = Model::createMultiple(Info::classname());
                Model::loadMultiple($modelsinfo, Yii::$app->request->post());

                // ajax validation
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ArrayHelper::merge(
                        ActiveForm::validateMultiple($modelsinfo),
                        ActiveForm::validate($model)
                    );
                }

                // validate all models
                $valid = $model->validate();
                $valid = Model::validateMultiple($modelsinfo) && $valid;
                
                if ($valid) {
                    $transaction = \Yii::$app->db->beginTransaction();
                    try {
                        if ($flag = $model->save(false)) {
                          
                            foreach ($modelsinfo as $key => $modelinfo) {
                                $modelinfo->step_id = $model->id;
                                
                                if (! ($flag = $modelinfo->save(false))) {

                                    $transaction->rollBack();
                                    break;

                                }
                                //error_log($transaction);
                            }
                        }
                        if ($flag) {
                            $transaction->commit();
                            return $this->redirect(['index', 'queue' => $queue]);
                        }
                    } catch (Exception $e) {
                        $transaction->rollBack();
                    }
                }

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'queue' => $queue,
            'modelsinfo' => (empty($modelsinfo)) ? [new Info] : $modelsinfo,
        ]);
    }

    /**
     * Updates an existing Step model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $modelsinfo = $this->findInfo($id);

        if ($model->load(Yii::$app->request->post())) {

            $oldIDs = ArrayHelper::map($modelsinfo, 'id', 'id');
            $modelsinfo = Model::createMultiple(Info::classname(), $modelsinfo);
            Model::loadMultiple($modelsinfo, Yii::$app->request->post());
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsinfo, 'id', 'id')));

            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelsinfo) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        if (!empty($deletedIDs)) {
                            Address::deleteAll(['id' => $deletedIDs]);
                        }
                        foreach ($modelsinfo as $modelinfo) {
                            $modelinfo->step_id = $model->id;
                            if (! ($flag = $modelinfo->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        
     

        return $this->render('update', [
            'model' => $model,
            'modelsinfo' => (empty($modelsinfo)) ? [new Info] : $modelsinfo
        ]);
    }

    /**
     * Deletes an existing Step model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Step model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Step the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Step::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function findInfo($id)
    {
      $model = Info::find()->where(['step_id' => $id])->all();
      return $model;
    }
}

views/step/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;

/* @var $this yii\web\View */
/* @var $model app\models\Step */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="step-form">

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>

    <div hidden>
    <?php echo $form->field($model, 'queue_id')->textInput(['value' => $queue]) ?>
    </div>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>


    <?php DynamicFormWidget::begin([
        'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
        'widgetBody' => '.container-items', // required: css class selector
        'widgetItem' => '.item', // required: css class
        'limit' => 10, // the maximum times, an element can be cloned (default 999)
        'min' => 0, // 0 or 1 (default 1)
        'insertButton' => '.add-item', // css class
        'deleteButton' => '.remove-item', // css class
        'model' => $modelsinfo[0],
        'formId' => 'dynamic-form',
        'formFields' => [
            'title',
            'type',
            
        ],
    ]); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-info"></i> &nbsp;Add Information
            <button type="button" class="pull-right add-item btn btn-success btn-xs"><i class="fa fa-plus"></i></button>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body container-items"><!-- widgetContainer -->
            <?php foreach ($modelsinfo as $index => $modelinfo): ?>
                <div class="item">
                    <?php
                        // necessary for update action.
                        if (!$modelinfo->isNewRecord) {
                            echo Html::activeHiddenInput($modelinfo, "[{$index}]id");
                        }
                    ?>
                   
                    <div class="row">
                    	
                        <div class="col-sm-5">
                        	 <?= $form->field($modelinfo, "[{$index}]title")->textInput(['maxlength' => true, 'placeholder' => 'Field'])->label(false); ?>
                        </div>
                        <div class="col-sm-5">
                            <?= $form->field($modelinfo, "[{$index}]type")->textInput(['maxlength' => true, 'placeholder' => 'Type'])->label(false); ?>
                        </div>
                        <div class="col-sm-1">
                        	<button type="button" class="pull-right remove-item btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                    		<div class="clearfix"></div>
                        </div>
                    </div>

                        
                    
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php DynamicFormWidget::end(); ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/step/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StepSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="step-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'queue_id') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/step/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Step */

$this->title = 'Create Step';
$this->params['breadcrumbs'][] = ['label' => 'Steps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="step-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'queue' => $queue,
        'modelsinfo' => (empty($modelsinfo)) ? [new Info] : $modelsinfo,
    ]) ?>

</div>

views/step/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\bootstrap\Modal;
/* @var $this yii\web\View */
/* @var $searchModel app\models\StepSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Steps';
$this->params['breadcrumbs'][] = $this->title;
?><br>
<div class="step-index">

    
    
    <?= Html::a('<i class="fa fa-plus"></i> Add Category', ['create', 'queue' => $queue], ['class' => 'btn btn-success btn-flat']) ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // 'queue_id',
            'name',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, app\models\Step $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

<?php 
    Modal::begin([
        'header' => '<h4>Points</h4>',
        'id' => 'modal',
        'size' => 'modal-lg',
    ]);
    echo "<div id='modalContent'></div>";


$script = <<< JS
    
    $(document).on('click','#modalButton', function(e){
    
        $('#modal').modal('show')
        .find('#modalContent')
        .load($(this).attr('value'));
    });
    
JS;
$this->registerJs($script);

 ?>

views/step/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;

/* @var $this yii\web\View */
/* @var $model app\models\Step */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="step-form">

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>
    <h3>Update</h3>
    <div hidden>
    <?php //echo $form->field($model, 'queue_id')->textInput(['value' => $queue]) ?>
    </div>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>


    <?php DynamicFormWidget::begin([
        'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
        'widgetBody' => '.container-items', // required: css class selector
        'widgetItem' => '.item', // required: css class
        'limit' => 10, // the maximum times, an element can be cloned (default 999)
        'min' => 0, // 0 or 1 (default 1)
        'insertButton' => '.add-item', // css class
        'deleteButton' => '.remove-item', // css class
        'model' => $modelsinfo[0],
        'formId' => 'dynamic-form',
        'formFields' => [
            'title',
            'type',
            
        ],
    ]); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-info"></i> &nbsp;Add Information
            <button type="button" class="pull-right add-item btn btn-success btn-xs"><i class="fa fa-plus"></i></button>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body container-items"><!-- widgetContainer -->
            <?php foreach ($modelsinfo as $index => $modelinfo): ?>
                <div class="item">
                    <?php
                        // necessary for update action.
                        if (!$modelinfo->isNewRecord) {
                            echo Html::activeHiddenInput($modelinfo, "[{$index}]id");
                        }
                    ?>
                   
                    <div class="row">
                    	
                        <div class="col-sm-5">
                        	 <?= $form->field($modelinfo, "[{$index}]title")->textInput(['maxlength' => true, 'placeholder' => 'Field'])->label(false); ?>
                        </div>
                        <div class="col-sm-5">
                            <?= $form->field($modelinfo, "[{$index}]type")->textInput(['maxlength' => true, 'placeholder' => 'Type'])->label(false); ?>
                        </div>
                        <div class="col-sm-1">
                        	<button type="button" class="pull-right remove-item btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                    		<div class="clearfix"></div>
                        </div>
                    </div>

                        
                    
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php DynamicFormWidget::end(); ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/step/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Step */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Steps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="step-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            
            'queue.name',
            'name',
        ],
    ]) ?>

    <div class="panel panel-default">
        <div class="panel-heading">Add information</div>
        <div class="panel-body">
            <?= Html::a('Create Information', ['/info/create', 'step' => $model->id], ['class' => 'btn btn-success']) ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchInfo,
                'columns' => [
                    //['class' => 'yii\grid\SerialColumn'],
                    'title',
                    'type',
                    [
                        'class' => ActionColumn::className(),
                        'urlCreator' => function ($action, app\models\Info $info, $key, $index, $column) {
                            return Url::toRoute(['/info/' .$action, 'id' => $info->id]);
                         }
                    ],
                ],
            ]); ?>
        </div>
    </div>

</div>