models/Queue.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tblqueue".
 *
 * @property int $id
 * @property int $status
 *
 * @property Tblstep[] $tblsteps
 */
class Queue extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tblqueue';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'status'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Queue',
            'status' => 'Status',
            'name' => 'Queue Name',
        ];
    }

    /**
     * Gets query for [[Tblsteps]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTblsteps()
    {
        return $this->hasMany(Step::className(), ['queue_id' => 'id']);
    }

    public function getSteps($queue){
        $step = Step::find()
        ->where(['queue_id' => $queue])
        ->count();
        $queue = Queue::find()
          ->where(['status' => 2])
          ->orderBy(['id' => SORT_DESC])
          ->count();

        $result = ($step > 0 && $queue == 0) ?  [1 => 'Draft', 2 => 'Posted'] : [1 => 'Draft'];
        return $result;
    }
}

models/Queues.php
<?php

namespace app\models;

use Yii;
use app\models\Station;


class Queues
{

    public function __construct($id, $queue) {
        $this->id = $id;
        $this->queue = $queue;
      }

 
 
}

controllers/QueueController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Info;
use app\models\InfoSearch;
use app\models\Model;
use app\models\Queue;
use app\models\QueueSearch;
use app\models\Step;
use app\models\StepSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * QueueController implements the CRUD actions for Queue model.
 */
class QueueController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                   // 'only' => ['logout'],
                    'rules' => [
                        [
                            'actions' => ['create', 'index', 'update', 'view', 'delete'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                        [
                            'actions' => ['login'],
                            'allow' => true,
                            // 'roles' => ['?'],
                        ],
                        
                    ],
                ],

                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Queue models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new QueueSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Queue model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $searchStep = new StepSearch();
        $dataProvider = $searchStep->search($id, $this->request->queryParams);
        $step = new Step();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'step' => $this->findStep($id),
            'searchStep' => $searchStep,
            'dataProvider' => $dataProvider,
            'step' => $step,
        ]);
    }

    /**
     * Creates a new Queue model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Queue();
        $step = [new Step];
        $info = [new Info];

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) ) {

                $step = Model::createMultiple(Step::classname());
                Model::loadMultiple($step, Yii::$app->request->post());

                $info = Model::createMultiple(Info::classname());
                Model::loadMultiple($info, Yii::$app->request->post());

                // ajax validation
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ArrayHelper::merge(
                        ActiveForm::validateMultiple($info),
                        ActiveForm::validateMultiple($step),
                        ActiveForm::validate($model)
                    );
                }

                // validate all models
                $valid = $model->validate();
                $valid = Model::validateMultiple($step) && $valid;
                $valid = Model::validateMultiple($info) && $valid;
                if ($valid) {
                    $transaction = Yii::$app->db->beginTransaction();
                    try {
                        if ($flag = $model->save(false)) {
                          
                            foreach ($step as $key => $stepz) {
                                $stepz->queue_id = $model->id;

                                
                                
                                if (! ($flag = $stepz->save(false))) {

                                    $transaction->rollBack();
                                    break;

                                }

                                foreach ($info as $key => $infoz) {
                                    $infoz->step_id = $stepz->id;
                                
                                    if (! ($flag = $infoz->save(false))) {
                                        $transaction->rollBack();
                                        break;
                                    }
                                }
                                //error_log($transaction);
                            }
                        }
                        if ($flag) {
                            $transaction->commit();
                            return $this->redirect(['step/index', 'queue' => $model->id]);
                        }
                    } catch (Exception $e) {
                        $transaction->rollBack();
                    }
                }

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'info' => (empty($info)) ? [new Info] : $info,           
            'step' => (empty($step)) ? [new Step] : $step,
        ]);
    }

    /**
     * Updates an existing Queue model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $queue = new Queue();
       
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Queue model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Queue model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Queue the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Queue::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

     protected function findStep($id)
    {
        if (($model = Step::findAll(['queue_id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }    
}

controllers/StepController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Info;
use app\models\InfoSearch;
use yii\helpers\ArrayHelper;
use app\models\Model;
use app\models\Step;
use app\models\StepSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * StepController implements the CRUD actions for Step model.
 */
class StepController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return 
        array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                   // 'only' => ['logout'],
                    'rules' => [
                        [
                            'actions' => ['create', 'index', 'update', 'view', 'delete'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                        [
                            'actions' => ['login'],
                            'allow' => true,
                            // 'roles' => ['?'],
                        ],
                        
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Step models.
     *
     * @return string
     */
    public function actionIndex($queue)
    {
        $searchModel = new StepSearch();
        $dataProvider = $searchModel->search($queue, $this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'queue' => $queue,
        ]);
    }

    /**
     * Displays a single Step model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $searchInfo = new InfoSearch();
        $dataProvider = $searchInfo->search($id, $this->request->queryParams);


        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchInfo' => $searchInfo,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Step model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($queue)
    {
        $model = new Step();
        $modelsinfo = [new Info];
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) ) {

                $modelsinfo = Model::createMultiple(Info::classname());
                Model::loadMultiple($modelsinfo, Yii::$app->request->post());

                // ajax validation
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ArrayHelper::merge(
                        ActiveForm::validateMultiple($modelsinfo),
                        ActiveForm::validate($model)
                    );
                }

                // validate all models
                $valid = $model->validate();
                $valid = Model::validateMultiple($modelsinfo) && $valid;
                
                if ($valid) {
                    $transaction = \Yii::$app->db->beginTransaction();
                    try {
                        if ($flag = $model->save(false)) {
                          
                            foreach ($modelsinfo as $key => $modelinfo) {
                                $modelinfo->step_id = $model->id;
                                
                                if (! ($flag = $modelinfo->save(false))) {

                                    $transaction->rollBack();
                                    break;

                                }
                                //error_log($transaction);
                            }
                        }
                        if ($flag) {
                            $transaction->commit();
                            return $this->redirect(['index', 'queue' => $queue]);
                        }
                    } catch (Exception $e) {
                        $transaction->rollBack();
                    }
                }

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'queue' => $queue,
            'modelsinfo' => (empty($modelsinfo)) ? [new Info] : $modelsinfo,
        ]);
    }

    /**
     * Updates an existing Step model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        $modelsinfo = $this->findInfo($id);

        if ($model->load(Yii::$app->request->post())) {

            $oldIDs = ArrayHelper::map($modelsinfo, 'id', 'id');
            $modelsinfo = Model::createMultiple(Info::classname(), $modelsinfo);
            Model::loadMultiple($modelsinfo, Yii::$app->request->post());
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsinfo, 'id', 'id')));

            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelsinfo) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        if (!empty($deletedIDs)) {
                            Address::deleteAll(['id' => $deletedIDs]);
                        }
                        foreach ($modelsinfo as $modelinfo) {
                            $modelinfo->step_id = $model->id;
                            if (! ($flag = $modelinfo->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        
     

        return $this->render('update', [
            'model' => $model,
            'modelsinfo' => (empty($modelsinfo)) ? [new Info] : $modelsinfo
        ]);
    }

    /**
     * Deletes an existing Step model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Step model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Step the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Step::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function findInfo($id)
    {
      $model = Info::find()->where(['step_id' => $id])->all();
      return $model;
    }
}

views/queue/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Queue */
/* @var $form yii\widgets\ActiveForm */
?>
<br><br>
<div class="queue-form">

	<h3>Queue</h3>
   <?php $form = ActiveForm::begin(); ?>
   <div class="col-sm-6">
<?php echo $form->field($model, 'name')->textInput([]) ?>	
   </div>
   <div class="col-sm-6">
    <?php  
    $data = [1 => 'Draft', 2 => 'Posted']; ?>
    <?= $form->field($model, "status")->dropDownList($model->getSteps($model->id), ['class' => 'form-control formula_input','prompt' => 'select status']); ?>
   </div>
      
  
    <div class="form-group">
        <?= Html::submitButton('Update', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/queue/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\QueueSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="queue-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/queue/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;
/* @var $this yii\web\View */
/* @var $model app\models\Queue */
/* @var $form yii\widgets\ActiveForm */
?>
<br>
<div class="queue-form">
 <h3>Create queue </h3>
    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>
    <div hidden>

     <?php echo $form->field($model, 'status')->textInput(['value' => 1]) ?>
    </div>
    <?php echo $form->field($model, 'name')->textInput([]) ?>
    <?php DynamicFormWidget::begin([
        'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
        'widgetBody' => '.container-items', // required: css class selector
        'widgetItem' => '.item', // required: css class
        'limit' => 10, // the maximum times, an element can be cloned (default 999)
        'min' => 1, // 0 or 1 (default 1)
        'insertButton' => '.add-item', // css class
        'deleteButton' => '.remove-item', // css class
        'model' => $step[0],
        'formId' => 'dynamic-form',
        'formFields' => [
            'name',
        
        ],
    ]); ?>
    <div class="panel panel-success">
        <div class="panel-heading">
            <i class="fa fa-info"></i> &nbsp; Categories
            <button type="button" class="pull-right add-item btn btn-success btn-xs"><i class="fa fa-plus"></i></button>
            <div class="clearfix"></div>
        </div>
        <div class="panel-body container-items"><!-- widgetContainer -->
            <?php foreach ($step as $index => $stepz): ?>
                <div class="item">
                    <?php
                        // necessary for update action.
                        if (!$stepz->isNewRecord) {
                            echo Html::activeHiddenInput($stepz, "[{$index}]id");
                        }
                    ?>
                   
                    <div class="row">
                         <div hidden>
                             <?= $form->field($stepz, "[{$index}]queue_id")->textInput(['maxlength' => true, 'placeholder' => 'Field', 'value' => Yii::$app->db->getLastInsertID()+1])->label(false); ?>
                        </div>
                        <div class="col-sm-10">
                             <?= $form->field($stepz, "[{$index}]name")->textInput(['maxlength' => true, 'placeholder' => 'Field'])->label(false); ?>
                        </div>
                        
                        <div class="col-sm-2 ">
                            <button type="button" class="pull-left remove-item btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                        <?php DynamicFormWidget::begin([
                            'widgetContainer' => 'dynamicform_wrapper_info',
                            'widgetBody' => '.container-info', // required: css class selector
                            'widgetItem' => '.info', // required: css class
                            'limit' => 10, // the maximum times, an element can be cloned (default 999)
                            'min' => 0, // 0 or 1 (default 1)
                            'insertButton' => '.add-info', // css class
                            'deleteButton' => '.remove-info', // css class
                            'model' => $info[0],
                            'formId' => 'dynamic-form',
                            'formFields' => [
                                'title',
                                'type',
                            
                            ],
                        ]); ?>
                        <div class="panel panel-default ">
                            <div class="panel-heading">
                                <i class="fa fa-info"></i> &nbsp; Add Information
                                <button type="button" class="pull-right add-info btn btn-success btn-xs"><i class="fa fa-plus"></i></button>
                                <div class="clearfix"></div>
                            </div>
                            <div class="panel-body container-info"><!-- widgetContainer -->
                                <?php foreach ($info as $index => $infoz): ?>
                                    <div class="info">
                                        <?php
                                            // necessary for update action.
                                            if (!$infoz->isNewRecord) {
                                                echo Html::activeHiddenInput($infoz, "[{$index}]id");
                                            }
                                        ?>
                                       
                                        <div class="row">
                                             <div >
                                                <?php  $form->field($infoz, "[{$index}]step_id")->textInput(['maxlength' => true, 'placeholder' => 'Field', 'value' => Yii::$app->db->getLastInsertID()+1])->label(false); ?>
                                            </div>
                                            <div class="col-sm-5">
                                                 <?= $form->field($infoz, "[{$index}]title")->textInput(['maxlength' => true, 'placeholder' => 'Title'])->label(false); ?>
                                            </div>
                                            <div class="col-sm-5">

                                                <?= $form->field($infoz, "[{$index}]type")->dropDownList(['Input' => 'Input', 'Number' => 'Number', 'Boolean' => 'Boolean'], ['maxlength' => true, 'placeholder' => 'type'])->label(false); ?>
                                                
                                            </div>
                                            
                                            <div class="col-sm-2">
                                                <button type="button" class="pull-right remove-info btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                                                <div class="clearfix"></div>
                                            </div>
                                            
                                        </div>

                                            
                                        
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <?php DynamicFormWidget::end(); ?>
                    

                        
                    
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php DynamicFormWidget::end(); ?>
   
    <p>You will be redirected to the list of categories to edit the information needed for each.</p>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    	
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/queue/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\QueueSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Queues';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="queue-index">
   
    <p>
        <?= Html::a('Create Queue', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
   
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           
            'name',
            [
                'label' => 'Status',
                'value' => function ($model) {
                    if ($model->status == 1)  {
                        return 'Draft';
                    }
                    else if ($model->status == 2){
                        return 'Posted';
                    }
                },

            ],
             [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, app\models\Queue $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/queue/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Queue */

$this->title = 'Update Queue: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Queues', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="queue-update">

  
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/queue/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Queue */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Queues', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="queue-view">


    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'label' => 'Status',
                'value' => function($model){
                    if ($model->status == 1){
                        return 'Draft';
                    }
                    else if ($model->status == 2){
                        return 'Posted';
                    }
                }
            ],
        ],
    ]) ?>
         
    <div class="panel panel-default">
        <div class="panel-heading">Categories</div>
        <div class="panel-body">
            <?= Html::a('Create categories', ['/step/create', 'queue' => $model->id], ['class' => 'btn btn-success']) ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchStep,
                'columns' => [
                    //['class' => 'yii\grid\SerialColumn'],
                    'name',
                    [
                        'class' => ActionColumn::className(),
                        'urlCreator' => function ($action, app\models\Step $step, $key, $index, $column) {
                            return Url::toRoute(['/step/' .$action, 'id' => $step->id]);
                         }
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>


<style>
.panel > .panel-heading {
/*    background-image: none;
    background-color: #00a65a;
    color: white;
*/
}
</style>