models/Station.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tblstation".
 *
 * @property int $id
 * @property int $queue_id
 * @property int|null $step_id
 * @property string $name
 *
 * @property Tblqueue $queue
 * @property Tblstep $step
 */
class Station extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    public $stationCustomers = [];
    public static function tableName()
    {
        return 'tblstation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['queue_id', 'name'], 'required'],
            [['queue_id', 'step_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['queue_id'], 'exist', 'skipOnError' => true, 'targetClass' => Queue::className(), 'targetAttribute' => ['queue_id' => 'id']],
            [['step_id'], 'exist', 'skipOnError' => true, 'targetClass' => Step::className(), 'targetAttribute' => ['step_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'queue_id' => 'Queue',
            'step_id' => 'Step',
            'name' => 'Name',
        ];
    }

    /**
     * Gets query for [[Queue]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getQueue()
    {
        return $this->hasOne(Queue::className(), ['id' => 'queue_id']);
    }

    /**
     * Gets query for [[Step]].
     *
     * @return \yii\db\ActiveQuery
     */

    public function getStep()
    {
        return $this->hasOne(Step::className(), ['id' => 'step_id']);
    }

    public function getAddcustomers($customer)
    {
        $this->stationCustomers->push($customer);
    }
}

models/Stations.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tblstation".
 *
 * @property int $id
 * @property int $queue_id
 * @property int|null $step_id
 * @property string $name
 *
 * @property Tblqueue $queue
 * @property Tblstep $step
 */
class Stations 
{
    /**
     * {@inheritdoc}
     */

   
   
    public function __construct($stationName) {
        $this->stationName = $stationName;
    }

   
   
}

controllers/StationController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Queue;
use app\models\Station;
use app\models\StationSearch;
use app\models\Step;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * StationController implements the CRUD actions for Station model.
 */
class StationController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Station models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new StationSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Station model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Station model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Station();
        $queue = new Queue();
        $step = new Step();
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'queue' => $queue, 
            'step' => $step,
        ]);
    }

    /**
     * Updates an existing Station model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $queue = new Queue();
        $step = new Step();
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'queue' => $queue, 
            'step' => $step,
        ]);
    }

    /**
     * Deletes an existing Station model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Station model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Station the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Station::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionStep()
    {

        $queue = Yii::$app->request->post('queue');

        $steps = Step::find()->select(['id','name'])->where(['queue_id'=>$queue])->all();
        $arr = [];
        $arr[] = ['id'=>'','text'=>''];
        foreach($steps as $step){
            $arr[] = ['id'=>$step->id,'text'=>$step->name];
            
        }
        \Yii::$app->response->format = 'json';
        \Yii::$app->response->formatters = [
            \yii\web\Response::FORMAT_JSON => [
                'class' => 'yii\web\JsonResponseFormatter',
                'encodeOptions' => JSON_UNESCAPED_UNICODE,
            ],
        ];
        return $arr;
    }

}

views/station/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\Arrayhelper;
/* @var $this yii\web\View */
/* @var $model app\models\Station */
/* @var $form yii\widgets\ActiveForm */

$typelist = \yii\helpers\Url::to(['station/step']); 

?>

<div class="station-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'queue_id')->widget(Select2::classname(), [
	    'data' => ArrayHelper::map($queue->find()->where(['status' => 2])->all(),'id','name'),
        'pluginOptions' => [
                'id' => 'queue',
                'name' => 'queue',
        ],
        'pluginEvents'=>[
            'select2:select'=>'function(){
                var vals = this.value;

                 $.ajax({
                    url: "'.$typelist.'",
                    data: {"queue":vals},    
                    type: "post",                         
                    success: function (result) {
                        console.log(result);
                        $(".step-select").html("").select2({ data:result, theme:"krajee", width:"100%",placeholder:"Select Step",
                            allowClear: false});
                        $(".step-select").select2("val","");
                    },
                    error: function (result) {
                        console.log(result);
                    }
                });


            }'
        ]	    
	]); ?>  

    <?= $form->field($model, 'step_id')->widget(Select2::classname(), [
        'data' => '',
        'options' => [
               // 'id' => 'step',
                'class' => 'step-select',
        ],
        //'data' => ArrayHelper::map($queue->find()->where(['status' => 2])->all(),'id','name'),
         
    ]); ?>  
    
    
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/station/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="station-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'queue_id') ?>

    <?= $form->field($model, 'step_id') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/station/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Station */

$this->title = 'Create Station';
$this->params['breadcrumbs'][] = ['label' => 'Stations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="station-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'queue' => $queue,
        'step' => $step,
    ]) ?>

</div>

views/station/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\StationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Stations';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="station-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Station', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            
            'queue.name',
            'step.name',
            'name',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, app\models\Station $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/station/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Station */

$this->title = 'Update Station: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Stations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="station-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'queue' => $queue, 
        'step' => $step,
    ]) ?>

</div>

views/station/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Station */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Stations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="station-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'queue_id',
            'step_id',
            'name',
        ],
    ]) ?>

</div>